// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkzujphqnkjhzbcsjhft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrenVqcGhxbmtqaHpiY3NqaGZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjcxMjAsImV4cCI6MjA2MzkwMzEyMH0.A7uvCd6CiHSvzzYEHhnx8LswqiwH58buyUuZ4ywgx7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);